rule VXVault_match
{
   meta:
        author = "iam-py-test"
        description = "Autogenerated YARA rule checking for URLs listed in VXVault"
        updated = "30/05/2026"
   strings:
   		$url1 = "http://5.252.155.72/load/os1/uRgOy.exe" ascii wide
		$url2 = "https://vcc-library.uk/Stb/Retev.php?bl=yQbDrnzZVH6cCtokqOPRE001.txt" ascii wide
		$url3 = "http://85.215.159.4:11029/stub.txt" ascii wide
		$url4 = "http://95.85.251.201/ourrat.exe" ascii wide
		$url5 = "http://95.85.251.201/Imperial.exe" ascii wide
		$url6 = "http://62.60.226.159/Amadey.x64.exe" ascii wide
		$url7 = "https://kokorostore.it/media/tXmCLyGO.exe" ascii wide
		$url8 = "http://77.110.126.212/5r3fqt67ew531has4231.arm" ascii wide
		$url9 = "https://cloudaxis.cc/gsmft/yueu/fkvqld/tvqqwh/ushu/22.exe" ascii wide
		$url10 = "http://45.133.74.103/x86" ascii wide
		$url11 = "https://marsalek.cy/static/abcfg.exe" ascii wide
		$url12 = "https://marsalek.cy/static/Pjibf2.exe" ascii wide
		$url13 = "http://190.198.218.210:1171/i" ascii wide
		$url14 = "http://176.97.210.242/bins/skid.x86" ascii wide
		$url15 = "https://raw.githubusercontent.com/lenkonftw/Project-Admini/refs/heads/main/pdf.exe" ascii wide
		$url16 = "https://raw.githubusercontent.com/lenkonftw/Project-Admini/refs/heads/main/decryptor.exe" ascii wide
		$url17 = "http://86.54.24.29/Renewable.exe" ascii wide
		$url18 = "http://178.16.55.189/amka/random.exe" ascii wide
		$url19 = "http://178.16.55.189/files/unique2/random.exe" ascii wide
		$url20 = "http://178.16.55.189/modka/duna.exe" ascii wide
		$url21 = "http://178.16.55.189/files/mr/random.exe" ascii wide
		$url22 = "http://178.16.55.189/files/8233900432/o7Hjuu7.exe" ascii wide
		$url23 = "http://216.126.239.11/alfa.exe" ascii wide
		$url24 = "http://172.86.123.179/inihiddenngentod/zerobotv9.x86_64" ascii wide
		$url25 = "https://bdddda.cfd/ddq1.exe" ascii wide
		$url26 = "https://hody-musique.com/modules/blog/oc.exe" ascii wide
		$url27 = "http://62.60.226.16:5553/dva.exe" ascii wide
		$url28 = "https://i-slept-with-ur.mom/Stb/Retev.php?bl=TGPEbjtXDrfj2U5fJTPRE008.txt" ascii wide
		$url29 = "https://vcc-library.uk/Stb/Retev.php?bl=QTuVl0PCseGLafunsZPRE008.txt" ascii wide
		$url30 = "http://176.46.152.62:5858/7526e77af84e4d3da650295a11488a99_crypted_build.exe" ascii wide
		$url31 = "http://178.16.55.189/files/6331503294/nGFFa2Q.exe" ascii wide
		$url32 = "http://178.16.55.189/files/5917492177/Mwt6qk5.exe" ascii wide
		$url33 = "http://144.172.107.244/frost.x86_64" ascii wide
		$url34 = "http://162.0.225.149/XjeelShZ/build.exe" ascii wide
		$url35 = "http://108.181.161.143:1911/build.exe" ascii wide
		$url36 = "http://178.16.55.189/files/7968590541/T7V02QZ.exe" ascii wide
		$url37 = "http://185.238.191.89:5554/beba.exe" ascii wide
		$url38 = "http://94.154.34.240:8000/Muzul.exe" ascii wide
		$url39 = "http://94.154.34.240:8000/Manya.exe" ascii wide
		$url40 = "http://94.154.34.240:8000/atrix.exe" ascii wide
		$url41 = "http://94.154.34.240:8000/linux.exe" ascii wide
		$url42 = "http://213.209.150.48/arm7" ascii wide
		$url43 = "http://185.39.207.117/ppc" ascii wide
		$url44 = "http://103.175.16.117/mips" ascii wide
		$url45 = "http://31.170.22.205/bins/whisper.x64" ascii wide
		$url46 = "http://196.251.115.212/x86_64" ascii wide
		$url47 = "https://github.com/deripascod/coderoom/raw/refs/heads/main/kythkkaewdth.exe" ascii wide
		$url48 = "https://raw.githubusercontent.com/XeroxzB/weqeq/main/XClient.exe" ascii wide
		$url49 = "http://62.60.226.112/file/590_9883.exe" ascii wide
		$url50 = "https://recursoscompartidos.xyz/pora/csc.exe" ascii wide
		$url51 = "http://176.65.134.5/arm" ascii wide
		$url52 = "http://176.65.134.62/bins/morte.x86" ascii wide
		$url53 = "http://hybridemails.ae/esign-app.exe" ascii wide
		$url54 = "http://37.44.238.88/l7vmra" ascii wide
		$url55 = "http://37.44.238.88/spim" ascii wide
		$url56 = "http://185.232.205.104/bins/g4za.arm7" ascii wide
		$url57 = "https://github.com/temperloin/piponis/raw/refs/heads/main/plrifjidicfid.exe" ascii wide
		$url58 = "https://github.com/temperloin/piponis/raw/refs/heads/main/jtunuhhrr.exe" ascii wide
		$url59 = "https://github.com/temperloin/piponis/raw/refs/heads/main/jrirkfiweid.exe" ascii wide
		$url60 = "http://filter.trueddns.com:18066/x/encode/ntoskrnl.b64" ascii wide
		$url61 = "https://github.com/BalletsPistol/d9fb74g8db7d8b7db48df7g8db77f4drb7er8db7fd84d7b1gdb47d8b7brt18bcy87gdfb8hfg74h87fh8bf18h7/raw/refs/heads/main/Encryptor.exe" ascii wide
		$url62 = "http://194.37.81.64/Aqua.x86_64" ascii wide
		$url63 = "http://185.81.68.147/Build.exe" ascii wide
		$url64 = "http://185.81.68.147/zx.exe" ascii wide
		$url65 = "http://185.81.68.147/ssg.exe" ascii wide
		$url66 = "http://185.81.68.147/Update.exe" ascii wide
		$url67 = "https://kiltone.top/stelin/Gosjeufon.cpl" ascii wide
		$url68 = "https://dominikatracy.com/audidg.exe" ascii wide
		$url69 = "http://zakazbuketov.kz/audiodf.exe" ascii wide
		$url70 = "http://80.82.65.70/dl?name=mixthree.exe^" ascii wide
		$url71 = "http://176.113.115.37/ScreenUpdateSync.exe" ascii wide
		$url72 = "http://185.81.68.147/gfx.exe" ascii wide
		$url73 = "http://185.81.68.147/ctx.exe" ascii wide
		$url74 = "http://185.81.68.147/AsyncClient.exe" ascii wide
		$url75 = "http://185.81.68.147/fcxcx.exe" ascii wide
		$url76 = "http://185.81.68.147/vvv.exe" ascii wide
		$url77 = "http://185.215.113.16/inc/Dynpvoy.exe" ascii wide
		$url78 = "http://74.50.95.117/files/Pkaffth.exe" ascii wide
		$url79 = "http://74.50.95.117/files/Hkrrl.exe" ascii wide
		$url80 = "http://45.131.135.227/Captcha.exe" ascii wide
		$url81 = "http://185.7.78.88/bot.arm" ascii wide
		$url82 = "https://mapimwp.org/wp-content/images/pic8.jpg" ascii wide
		$url83 = "https://nasa.r2cloudhikepoo2.shop/NHFMUBEFH4C9ARNQC6U9.bin" ascii wide
		$url84 = "http://83.217.208.37/app/upd.exe" ascii wide
		$url85 = "https://durraactive.com.my/wp-content/images/pic11.jpg" ascii wide
		$url86 = "http://66.63.187.231/657/caspol.exe" ascii wide
		$url87 = "http://66.63.187.150/file/build3.exe" ascii wide
		$url88 = "http://66.63.187.150/file/build2.exe" ascii wide
		$url89 = "http://66.63.187.150/file/build.exe" ascii wide
		$url90 = "https://aquafusion.com.co/ngbx/ngown.exe" ascii wide
		$url91 = "http://59.99.215.146:49697/Mozi.m" ascii wide
		$url92 = "https://github.com/clipaCHEAT/chaaa/raw/refs/heads/main/Built.exe" ascii wide
		$url93 = "https://github.com/Abdulah345/pizdaporc/raw/refs/heads/main/XClient.exe" ascii wide
		$url94 = "https://newvideo.link/temp/xnsjjxja.exe" ascii wide
		$url95 = "http://185.215.113.16/off/def.exe" ascii wide
		$url96 = "https://dewatabalirental.com/4.exe" ascii wide
		$url97 = "https://dewatabalirental.com/3.exe" ascii wide
		$url98 = "https://dewatabalirental.com/2.exe" ascii wide
		$url99 = "https://dewatabalirental.com/1.exe" ascii wide
		$url100 = "https://samzafood.com.my/wp-content/images/pic5.jpg" ascii wide
		$url101 = "https://samzafood.com.my/wp-content/images/pic6.jpg" ascii wide

   condition:
        any of them
}
